### ISSUE TITLE
Should this be hard coded to `us-west-2`?

### ISSUE THREAD

**Issue by roskelleycj** [cdklabs/cdk-pipelines-github#149]
[This][1] shows that `us-west-2` is the region that will be set when the file assets are being transferred.  This is typically not a good idea for S3 clients to be fixed to one region, especially when the S3 assets are could be in other regions.  Wondering if this shouldn't be taken from the 'env' instead?  Looking at the deploy step it uses the env region.

[1]:  https://github.com/cdklabs/cdk-pipelines-github/blob/f37851a4940b402dd156d974ce82e3570cc2f26b/src/pipeline.ts#L347

**Comment by kaizen3031593** [comment]
Hi again, @roskelleycj. The code you linked, 
https://github.com/cdklabs/cdk-pipelines-github/blob/f37851a4940b402dd156d974ce82e3570cc2f26b/src/pipeline.ts#L347

actually concerns authenticating GitHub to AWS, not where s3 assets are published. In the end, the region gets bundled into a parameter for the [Configure AWS Credentials](https://github.com/aws-actions/configure-aws-credentials) GitHub action. The action requires a region, but we don't really care what region it is since all we are doing is authenticating.

Follow up question: where do the s3 assets get stored? This actually comes from this line,

https://github.com/cdklabs/cdk-pipelines-github/blob/f37851a4940b402dd156d974ce82e3570cc2f26b/src/pipeline.ts#L311

which calls the `cdk-assets` CLI. What this does is that it finds the asset manifest in your `cdk.out` folder, and creates a shell script that looks something like this:

```sh
set -x
npx cdk-assets --path "cdk.out/assembly-StageA/StageAFunctionStackD42C27B8.assets.json" --verbose publish "<hash>:<account-id>-us-east-1"
npx cdk-assets --path "cdk.out/assembly-StageB/StageBFunctionStack18098DCD.assets.json" --verbose publish "<hash>:<account-id>-eu-west-1"
echo '::set-output name=asset-hash::923d41051861c9ea2fa3f60c36c4c5a7f10bdf4fa44ed6965ba3a7bfe50f0487'
```

In this example, we are actually publishing the same asset to two different regions.

**Comment by roskelleycj** [comment]
@kaizen3031593 thank you for the details.
